### ISSUE TITLE
Add Compliance subpage

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/filplus-dashboard-webapp#11]
From the main page there should be a subpage on Compliance. 

As we work on the graphs for now, this should allow user to enter a name or an ID of an allocator or Client and run a compliace report on them. Expected behaviour:

- I open the page and see a search box, where I enter the name, part of the name or an ID. 
- The system finds all possible matches for client/allocator, so if I search for "allocator" I will get suggestion of 
f03016877| Blockchain Worl...| Blockchain World News |
f03018484 | BDX Fil+ Allocator | BigData Exchange |
f03018489 | Caro Allocator |   |
f02849382 | Kernelogic Fil+... | Kernelogic |
f03019833 | Deprecated - Be... | Bewell Technology Limited |
f03019921 | OpenGate Dataca... | OpenGate |
f02903211 | EasyOnboard Allocator | Tech Greedy | 0
f03019831 | Venus Fil+ Data... | Venus Team |
f03019934 | FBG Allocator| FBG Capital |

- I can click on any of them and get a "generate a compliance report" which runs the report and opens a new tab with https://compliance.allocator.tech/report/f03016877/1721224205/report.md

Some of this functionality already exists at https://compliance.allocator.tech/. But the search and more sleek UI are needed.

**Comment by tplocic20** [comment]
Redundand for now @martapiekarska
