### ISSUE TITLE
Add compliance dashboards

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/filplus-dashboard-webapp#14]
We need to replace compliance.datacapstats.io with http://datacapstats.io/compliance for 1) SPs and 2) Allocators. The metrics we would like to present on dashboards are as follows:
## SPs
_this is aggregated view of the general "health" of the program, not per SP view_
### Graph 1: Retrievability score

- \# of SPs with above average score
- \# of SPs with around average score
- \# of SPs with below average score
### Graph 2: \# of Deals:

- \# of SPs with more than 3 clients
- \# of SPs with 1-3 clients
- \# of SPs with  only 1 client

### Graph 3: Size of the biggest deal

- \# of SPs with biggest deal size being max 30% of total deals made
- \# of SPs with biggest deal size being 30-50% of total deals made
- \# of SPs with biggest deal size being more than 50% of total deals made.

### (Maybe) Graph 4: Transparent Client Base
- \# of SPs with transparent Client Base
- \# of SPs who do not reveal their Client Base

### Graph 1: Retrievability score (averaged over SPs that the allocator is working with)

- \# of Allocators with above average score
- \# of Allocators with around average score
- \# of Allocators with below average score

### Graph 2:Size of the biggest allocation

- \# of Allocators with biggest allocation max 30% of total DC Allocation
- \# of Allocators with biggest allocation 30-50% of total DC Allocation
- \# of Allocators with biggest allocation using more than 50% of total DC Allocation

### Graph 3: SP compliance

- \# of Allocators with 80% SPs likely being in compliance (meeting 3 of compliance metrics)
- \# of Allocators with 40-80% SPs  likely being in compliance (2 out of 3 compliance metrics)
- \# of Allocators with <40% SPs likely being in compliance (1 or 0 out of 3 compliance metrics)

**Comment by smooth-operator** [comment]
For graph 3 from the SPs tab, do you mean individual deals or total dc received from a client? Individual deals are usually 32gb in order to fill a sector as it can be seen here: https://filfox.info/en/deal.

**Comment by martapiekarska** [comment]
I mean to show that the SP didn't receive all of their DC from one client. Imagine the following situation:
Deal 1: 1PiB from Client 1
Deal 2: 1.5PiB from Client 2
Deal 3: 3PiB from Client 3
Deal 1: 0.5PiB from Client 1
Deal 4: 1PiB from Client 1
Deal 5: 2PiB from Client 1
Total DC received: 9PiB, Biggest allocation: 4.5PiB from Client 1. this means that this SP received 50% of total DC from one client

**Comment by martapiekarska** [comment]
Also, would be good to include a graph on the audit success:
\# of Allocators who passed the audit
\# of Allocators who have "yellow card" - they passed conditionally
\# of Allocators who failed the audit
\# of Allocators who have not been audited

**Comment by tplocic20** [comment]
@martapiekarska We will discuss this today on the Neti - FIDL checkin - as we need to spec the api properly

**Comment by martapiekarska** [comment]
There are two more things here:

1. we need to account for new SPs - if I am new to the system none of the metrics will apply to me. This probably should be tackled by two things:
a) A graph showing the "age of an SP" (need a better name): SPs who have joined <3months; SPs who have been participating 3-12 months; SPs who have been in Filecoin >12 months
b) To each of the graphs in SP compliance part we need to add a fourth choice:
 - Retrieval: "No retrievability Score"
 - \# of Deals: "No deals, too new SP"
 - Size of the biggest deal: "No deals, too new SP"
 
2. We need a graph that will show the quality of data onboarded. Ideally this will be done by day and shows a division by the "compliance of SPs" of how much data is onboarded - eg.  czyli np 30% data on 12.08 was onboarded by "compliant SPs (meeting the metrics)"; 50% come from "non-compliant SP", 20% comes from unknown (new or meeting only 1 compliance metrics)

![image](https://github.com/user-attachments/assets/28e3f5ec-35c9-4d35-b580-0f250d4fb08c)

**Comment by tplocic20** [comment]
@martapiekarska 
What data we have and what we will prepare: 

From the initial Issue 
- SP graphs 1, 2, 3
- Allocators graphs 1, 2, 3

From comment: https://github.com/fidlabs/filplus-dashboard-webapp/issues/14#issuecomment-2271484317
- We do not have the audit success data in the allocator.tech - but we can temporarily reuse data from the DMOB api (for the tree charts)

The last comment is not yet included. We can add this but when having the new CDP API ready.

As for the priorities - I am going to implement them going top-bottom, if you want to switch the priority - let me know.
