### ISSUE TITLE
In the main page

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/filplus-dashboard-webapp#16]
Add filtering option to the graph representing weekly DC allocation by allocator. When I click on a week in the legend I would like to be able to only see allocations made in that week
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/97e40b8f-80e1-427b-a0c9-1f3d6e9b4ef7">

**Comment by tplocic20** [comment]
@martapiekarska But you would like to see the same graph but filtered to only show bars for the selected week?
Or raw data table with the allocations list?

1. Is doable now 
2. would need a new data endpoints
