### ISSUE TITLE
Incorrect DataCap remaining displayed

### ISSUE THREAD

**Issue by martplo** [fidlabs/filplus-dashboard-webapp#21]
DataCap remaining displays an incorrect value. [Example](https://datacapstats.io/clients?filter=f1rriorjgkxfktrdrjusgplm3yx4wr7cpjumol5aa)

**Comment by smooth-operator** [comment]
For the attached example verify.glif.io returns the same value for remaining datacap 
![image](https://github.com/user-attachments/assets/241eb9e8-3e4f-4bfa-bfa8-24062bbe9bd9)

I think we might have an issue with "datacap used in the last 2 weeks" field. Will investigate.

**Comment by martplo** [comment]
There was another allocation today, so it should be 2000 TiB received, and 1000 TiB remained.

**Comment by smooth-operator** [comment]
It's there now. We don't display real time data on datacapstats, we show cached data. Also, the various pieces of data that we display are acquired through cron jobs that run at varied intervals, so it takes a bit for an allocation to make it to the client page.

**Comment by tplocic20** [comment]
@martplo Can you confirm that the data is now in sync?

**Comment by martplo** [comment]
Seems to display correct data now.
