### ISSUE TITLE
On individual client page 

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/filplus-dashboard-webapp#4]
Add a Graph Part which shows the breakdown of the DC this client spend by storage provider

**Comment by tplocic20** [comment]
@smooth-operator Are we able to get this data from `getDealAllocationStats/{clientId}`?

**Comment by tplocic20** [comment]
@martapiekarska As for the UI/UX side - how about we change the SP breakdown and Allocations breakdown lists with the graphs?

The pie chart for SP Breakdown 
And stacked bar/line chart for Allocations breakdown. So we will show how the total DC changed and also show the size of individual allocations

**Comment by martapiekarska** [comment]
That works for me @tplocic20 - where are we with it?
